export type Role =
  | "OWNER_OPERATOR"
  | "PROPERTY_MANAGER"
  | "CLEANING_COORDINATOR"
  | "CLEANER"
  | "VENDOR"
  | "OPS_MANAGER";

export type AgentType =
  | "LEAD_TURNOVER_OPS"
  | "BOOKING_SYNC"
  | "SOP"
  | "SOW"
  | "CLEANING_SCHEDULER"
  | "CLEANER_DISPATCH"
  | "CHECKLIST_QA"
  | "PHOTO_VERIFICATION"
  | "ISSUE_ESCALATION"
  | "INVENTORY_RESTOCK"
  | "OWNER_UPDATE";

export type TurnoverStatus =
  | "SCHEDULED"
  | "ASSIGNED"
  | "IN_PROGRESS"
  | "QA_PENDING"
  | "ISSUES_OPEN"
  | "COMPLETED"
  | "CANCELLED"
  | "OVERDUE";
